# Generated by Django 5.2.16 on 2026-07-21 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_alter_globalpagepermission_can_view_and_more'),
        ('djcms_markdown', '0002_auto_20180404_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsmarkdownplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin'),
        ),
    ]
